apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pshr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-pshr@sha256:32c953c533aaf6dbb5c3a6a49b0acebfe3baff259f91cf0f67b41b747e8f1df8
        name: my-nodejs
        resources: {}
status: {}
